# Generated by Django 3.2.7 on 2021-09-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='date',
            new_name='paid_date',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='price',
            new_name='paid_price',
        ),
    ]
