gradovi = ['Banja Luka', 'Berkovići', 'Bijeljina', 'Bileća', 'Bosanska Dubica', 'Bosanska Gradiška', 'Bosanska Kostajnica',
'Bosanska Krupa', 'Bosanski Brod', 'Bosanski Novi',
'Bosanski Šamac',
'Bratunac',
'Čajniče',
'Čelinac',
'Derventa',
'Doboj',
'Donji Žabar',
'Foča',
'Gacko',
'Han-Pijesak',
'Istočna Ilidža',
'Istočni Drvar',
'Istočni Mostar (općina)',
'Istočni Stari Grad',
'Istočno Novo Sarajevo',
'Jezero',
'Kalinovik',
'Kotor-Varoš',
'Kupres (RS)',
'Laktaši',
'Lopare',
'Ljubinje',
'Milići',
'Modriča',
'Mrkonjić Grad',
'Nevesinje',
'Novo Goražde',
'Osmaci',
'Oštra Luka',
'Pale',
'Pelagićevo',
'Petrovo',
'Prijedor',
'Prnjavor',
'Ribnik',
'Rogatica',
'Rudo',
'Skender Vakuf',
'Sokolac',
'Srbac',
'Srebrenica',
'Srebrenik',
'Šekovići',
'Šipovo',
'Teslić',
'Trebinje',
'Trnovo (RS)',
'Ugljevik',
'Višegrad',
'Vlasenica',
'Vukosavlje',
'Zvornik']

print(len(gradovi))